export { default as IC_ChevronDownDark } from "./ic_chevron-down-dark.svg";
export { default as IC_FontSizeDecrease } from "./ic_font-size-decrease.svg";
export { default as IC_FontSizeIncrease } from "./ic_font-size-increase.svg";
export { default as IC_TextToSpeech } from "./ic_text-to-speech.svg";
export { default as IC_Translate } from "./ic_translate-dark.svg";
export { default as IC_Target } from "./ic_target.svg";
export { default as IC_Gift } from "./ic_gift.svg";
export { default as IC_Flag } from "./ic_flag.svg";
export { default as IC_Volunteer } from "./ic_volunteer.svg";
export { default as IC_Community } from "./ic_commnuity.svg";
export { default as IC_Handshake } from "./ic_handshake.svg";
export { default as IC_Hamburger } from "./ic_hamburger.svg";
export { default as IC_Play } from "./ic_play.svg";
// export { default as } from './'
